### ISSUE TITLE
previousRequest deprecated?

### ISSUE THREAD

**Issue by w0bbes** [pagekit/vue-resource#338]
Hey!

Just upgraded to 0.9.3. It seems previousRequest is deprecated? This was my working code:

`Vue.http.patch('/api/someurl, proposalDetails, {`
`before (request) {`
`if (this.previousRequest) {`
`this.previousRequest.abort()`
`}`
`this.previousRequest = request`
`}`
`}).then((response) => {}, (error) => {})`

Any info on this or am I being an idiot?

**Comment by amostajo** [comment]
Request parameters changed in new version.

I am having the same problem. But design decision imo.

For instance, when you had this:
```
this.$http.get('some/url', myParams);
```

Has to be changed to:

```
this.$http.get('some/url', {params:myParams});
```

For POST is different though, seems like you have to use `body` now....

I really liked how versatile previous version was in comparison to this one in this aspect. In my honest opinion this is a step backwards.

**Comment by w0bbes** [comment]
Thanks for the responds @amostajo, not sure why this is changed either.

**Comment by w0bbes** [comment]
I still did not manage to get around this. The [recipe here](https://github.com/vuejs/vue-resource/blob/master/docs/recipes.md) says it should work although previousRequest doesnt exist.

Anyway managed to abort previous requests?

**Comment by w0bbes** [comment]
Fixed it, im a tard indeed

**Comment by w0bbes** [comment]
close please

**Comment by fntneves** [comment]
I am still having issues understanding how can I abort a request using "before" callback.
