### ISSUE TITLE
Typescript definitions not working?

### ISSUE THREAD

**Issue by clementdevos** [pagekit/vue-resource#673]
Hey guys! 

I'm currently trying to upgrade our project running  vue 2.3x to vue 2.5.13 and i can't make it use VueRessource. 

My vue imports and use are declared this way 

```
import Vue from 'vue';
import VueRouter from 'vue-router';
import VueResource from 'vue-resource';
import Vue2Filters from 'vue2-filters';
import { Validator } from 'vee-validate';
import BootstrapVue from "bootstrap-vue";
import VueI18n from 'vue-i18n';


Vue.use(Vue2Filters);
Vue.use(VueResource);
Vue.use(VueRouter);
Vue.use(VueI18n);
Vue.use(infiniteScroll);
Vue.use(BootstrapVue);
```

But the TS compilation fails with the following error : 

```
(61,9): error TS2345: Argument of type 'typeof "/home/clement/workspace/pingflow/v3/fry/node_modules/vue-resource/types/index"' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
  Type 'typeof "/home/clement/workspace/pingflow/v3/fry/node_modules/vue-resource/types/index"' is not assignable to type 'PluginFunction<any>'.
    Type 'typeof "/home/clement/workspace/pingflow/v3/fry/node_modules/vue-resource/types/index"' provides no match for the signature '(Vue: VueConstructor<Vue>, options?: any): void'.
```

I'm running the latest libraries versions : vue@2.5.13 and vue-resource@1.3.6

Cheers, 

Clément

**Comment by prasadrajandran** [comment]
Hey,

Not sure why this isn't getting more attention, but downgrading to [v1.3.5](https://github.com/pagekit/vue-resource/tree/1.3.5) worked for me. They added TypeScript typings to [v1.3.6+](https://github.com/pagekit/vue-resource/releases/tag/1.3.6) (see [commit](https://github.com/pagekit/vue-resource/commit/c56d25c333530aa5151201cb6b076b4ab1bafbbe)), so I'm guessing there's something not quite right with the typings?

**Comment by clementdevos** [comment]
I ended up doing the same thing...

**Comment by huysamen** [comment]
Same issue here.

**Comment by krishghata** [comment]
Hi I am still getting this error :

Console:
======
Argument of type 'typeof "D:/Workshop/nodejs/ef-web-components/node_modules/vue-resource/types/index"' is not assig
nable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
  Type 'typeof "D:/Workshop/nodejs/ef-web-components/node_modules/vue-resource/types/index"' is not assignable to type 'Pl
uginFunction<any>'.
    Type 'typeof "D:/Workshop/nodejs/ef-web-components/node_modules/vue-resource/types/index"' provides no match for the s
ignature '(Vue: VueConstructor<Vue>, options?: any): void'.
     178 |
     179 |     import VueResource from 'vue-resource';
  > 180 |     Vue.use(VueResource);


Component:
=========
import VueResource from 'vue-resource';
Vue.use(VueResource);


package.json
=========
{
  "name": "ef-web-components",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "bootstrap": "^4.0.0",
    "jquery": "^3.3.1",
    "luxon": "^1.0.0",
    "moment": "^2.22.0",
    "popper.js": "^1.14.1",
    "vue": "^2.5.13",
    "vue-class-component": "^6.0.0",
    "vue-click-outside": "^1.0.7",
    "vue-datetime": "^1.0.0-beta.3",
    "vue-property-decorator": "^6.0.0",
    "vue-resource": "^1.5.0",
    "weekstart": "^1.0.0"
  },
  "devDependencies": {
    "@types/node": "^9.6.2",
    "@vue/cli-plugin-babel": "^3.0.0-beta.6",
    "@vue/cli-plugin-typescript": "^3.0.0-beta.6",
    "@vue/cli-service": "^3.0.0-beta.6",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "vue-template-compiler": "^2.5.13"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by NateScarlet** [comment]
@krishghata  Fixed in 1.5.1, you are using 1.5.0, you can manully copy the files in https://github.com/pagekit/vue-resource/tree/develop/types or use my fork by: `npm install https://github.com/NateScarlet/vue-resource/tarball/1.5.1`

**Comment by csr632** [comment]
Using 1.5.1, still can't access $http or http in Vue.
![screenshot](https://user-images.githubusercontent.com/18747423/41217251-eee692de-6d89-11e8-9276-ce228429c2a0.png)

I have import and use vue-resource in main.ts:
![](https://user-images.githubusercontent.com/18747423/41217328-167bbf04-6d8a-11e8-987e-efbd6cf708f1.png)

according to [vue docs](https://vuejs.org/v2/guide/typescript.html) , someone have to do something like:
```ts
declare module 'vue/types/vue' {
  // Global properties can be declared
  // on the `VueConstructor` interface
  interface VueConstructor {
    $myGlobal: string
  }
}
```
But [vue-resource](https://github.com/pagekit/vue-resource/blob/6072148a56ac35fd1f599d80000f02cf15df47fe/types/vue.d.ts) is not doing something like this, which make $http not accessable from global `Vue`.

**Comment by csr632** [comment]
As a temporary workaround, I manually add some declaration to [projectRoot/node_modules/vue-resource/types/vue.d.ts](https://github.com/pagekit/vue-resource/blob/6072148a56ac35fd1f599d80000f02cf15df47fe/types/vue.d.ts#L14):
```ts
/**
 * Extends interfaces in Vue.js
 */

import Vue from "vue";
import { HttpHeaders, HttpOptions, HttpResponse, $http, $resource } from "./vue_resource";

declare module "vue/types/options" {
    interface ComponentOptions<V extends Vue> {
        http?: (HttpOptions & { headers?: HttpHeaders } & { [key: string]: any })
    }
}

declare module "vue/types/vue" {
    interface Vue {
        $http: {
            (options: HttpOptions): PromiseLike<HttpResponse>;
            get: $http;
            post: $http;
            put: $http;
            patch: $http;
            delete: $http;
            jsonp: $http;
        };
        $resource: $resource;
    }

    interface VueConstructor {
        http: {
            (options: HttpOptions): PromiseLike<HttpResponse>;
            get: $http;
            post: $http;
            put: $http;
            patch: $http;
            delete: $http;
            jsonp: $http;
        };
        resource: $resource;
    }
}
```

**Comment by gspinella** [comment]
I've made a workarond by casting Vue to 'any' like this:
> (<any>Vue).http.options.root = "http://localhost:3000/";
This removed the error message from TS compiler.

**Comment by VasiliyLazarev-IBM** [comment]
Same problem:
![image](https://user-images.githubusercontent.com/42234190/49861477-fa778680-fe0c-11e8-8441-eb7dff487d07.png)

```
typescript@3.2.1
vue@2.5.17
vue-svgicon@3.2.2
```

**Comment by boreq** [comment]
Problem still persists @steffans, I am not sure why this is closed.

    typescript@3.3.3
    vue-resource@1.5.1

**Comment by sebasijan** [comment]
I am still getting this stupid error 

vue 1.2.13 
vue-resource v1.53
